
export const laws = [
    "RA 10121",
    "EO 51",
    "PD No. 603",
    "AO 0013-2013",
    "RA 11332",
    "RA No. 73",
    "AO 2006-0012",
    "RA 10028",
    "RA 1082",
    "AO 2005-0014",
    "RA 10821",
    "AO 34-A 3 2000",
    "PD 651",
    "RA 7600",
    "RA 9211",
    "AO 2017-0012",
    "RA 2029",
    "RA 10354",
    "EO 382",
    "RA 7610",
    "AO 2006-0015",
    "RA 7160",
    "RA 7305",
    "PD No. 825",
    "RA 771",
    "RA 2382",
    "RA 9502",
    "RA 7432",
    "PD No. 79",
    "RA 6713",
    "RA 8423",
    "RA 6425",
    "AO 2009-0025",
    "AO 36 8010",
    "RA 8172",
    "RA 3573",
    "PD No. 856",
    "RA 9262",
    "RA 10666",
    "PD No. 965",
    "AO 2008-0029",
    "RA 9165",
    "LOI No. 949",
    "RA 7277",
    "RA 6675",
    "PD No. 996",
    "RA 7846",
    "RA 8980",
    "RA 7875",
    "RA 9288",
    "RA 8749",
    "RA 8976",
    "Ministry Circular No. 2 of 1986"
];

export const descriptions = [
    "Philippine Disaster Risk Reduction and Management Act",
    "Philippine Milk Code",
    "Child and Youth Welfare Code",
    "Guidelines for Infection Prevention in Healthcare Settings",
    "Mandatory Reporting of Notifiable Diseases Act",
    "Statistical Data Collection Act",
    "National Health Insurance Program Guidelines",
    "Expanded Breastfeeding Promotion Act",
    "Rural Health Act",
    "Newborn Screening Guidelines",
    "Children's Emergency Relief and Protection Act",
    "Hospital Waste Management Guidelines",
    "Birth Registration Act",
    "Rooming-In and Breastfeeding Act",
    "Tobacco Regulation Act",
    "Disaster Risk Management for Health Sector",
    "Anti-Tuberculosis Act",
    "Responsible Parenthood and Reproductive Health Act",
    "Housing Development Policy",
    "Special Protection of Children Against Abuse Act",
    "Non-Communicable Disease Prevention Guidelines",
    "Local Government Code",
    "Magna Carta of Public Health Workers",
    "Anti-Littering Law",
    "National Blood Services Act",
    "Medical Act of the Philippines",
    "Cheaper Medicines Act",
    "Senior Citizens Act",
    "Responsible Parenthood and Family Planning Act",
    "Code of Conduct and Ethical Standards for Public Officials",
    "Traditional and Alternative Medicine Act",
    "Dangerous Drugs Act",
    "Hospital Licensing Guidelines",
    "Local Health System Integration Guidelines",
    "ASIN Law (Salt Iodization Act)",
    "Law on Reporting Notifiable Diseases",
    "Sanitation Code of the Philippines",
    "Anti-Violence Against Women and Their Children Act",
    "Children’s Safety on Motorcycles Act",
    "Pre-Marital Counseling Act",
    "Magna Carta for Public Health Workers Implementation Guidelines",
    "Comprehensive Dangerous Drugs Act",
    "Barangay Health Workers Program",
    "Magna Carta for Disabled Persons",
    "Generics Act of 1988",
    "Compulsory Immunization for Children Act",
    "Compulsory Hepatitis B Immunization Act",
    "Early Childhood Care and Development Act",
    "National Health Insurance Act (PhilHealth)",
    "Newborn Screening Act",
    "Clean Air Act",
    "Philippine Food Fortification Act",
    "Drug Production and Quality Standards Regulation"
];
